src/Proyecto_API/Proyecto_API/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # Utiliza la expresión regular dentro de re_path()
    urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),]

else:
    urlpatterns += [path('static/', serve, {'document_root': settings.STATIC_ROOT}),]

src/Proyecto_API/api/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import *

app_main = "main"

urlpatterns=[
    # Login
    path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    # URLs Productos
    path('articulos/', ArticuloView.as_view(), name='articulo_list'),
    path('articulos/<int:id>', ArticuloView.as_view(), name='articulo_process'),
    # URLs Facturas
    path('facturas/', FacturaView.as_view(), name='factura_list'),
    path('facturas/<int:id>', FacturaView.as_view(), name='factura_process'),
    # URLs Proveedores
    path('proveedores/', ProveedorView.as_view(), name='proveedor_list'),
    path('proveedores/<int:id>', ProveedorView.as_view(), name='proveedor_process'),
    # URLs Direccion
    path('direccion/', DireccionView.as_view(), name='direccion_list'),
    path('direccion/<int:id>', DireccionView.as_view(), name='direccion_process'),
    # URLs Plantillas
    path("home", Home, name="home"),
    path("ingresos", Ingresos, name="ingresos"),
    path('egresos', Egresos, name='egresos'),
    # ARTICULOS
    path("articulos/views", Products, name="articulos"),
    path('articulos/add', crear_articulo, name='crear_articulo'),
    path('articulos/edit/<int:id>', editar_articulo, name='editar_articulo'),
    path('articulos/delete/<int:id>', eliminar_articulo, name='eliminar_articulo'),
    # FACTURAS
    path("facturas/views", Facturas, name="facturas"),
    path('facturas/add', crear_factura, name='crear_factura'),
    path('facturas/edit/<int:id>', editar_factura, name='editar_factura'),
    path('facturas/delete/<int:id>', eliminar_factura, name='eliminar_factura'),
    # DIRECCION
    path('proveedor/add', crear_proveedor, name='crear_proveedor'),
    path('direccion/add', crear_direccion, name='crear_direccion'),
    # CATEGORIAS
    path('categorias/views', Catergorias, name='categorias'),
    # LOGS
    path('registros', logs_view, name='registros'),
]

src/Proyecto_API/api/models.py
from django.db import models, transaction
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import pre_save
from django.dispatch import receiver

# Create your models here.

class Direccion(models.Model):
    calle = models.CharField(max_length=50)
    numero = models.PositiveIntegerField()
    comuna = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.calle}, {self.numero}, {self.comuna}"

class Proveedor(models.Model):
    rut = models.CharField(max_length=50)
    nombre = models.CharField(max_length=100)
    giro = models.CharField(max_length=100)
    correo = models.EmailField(max_length=100)
    telefono = models.CharField(max_length=20)
    celular = models.CharField(max_length=20)
    web = models.URLField(max_length=100)
    direccion = models.OneToOneField(Direccion, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    def clean(self):
        if isinstance(self.rut, str):
            self.rut = self.rut.replace('.', '').replace('-', '')  # Eliminar puntos y guión
            self.rut = self.rut[:-1] + '-' + self.rut[-1]  # Agregar guión antes del dígito verificador
            self.rut = self.rut.upper()  # Convertir a mayúsculas (opcional)
        else:
            raise ValidationError('RUT inválido')

        rut_numero, rut_digito = self.rut.split('-')  # Separar número y dígito verificador

        # Validar longitud y formato del número y dígito verificador
        if not rut_numero.isdigit() or not rut_digito.isdigit() or len(rut_digito) > 1:
            raise ValidationError('RUT inválido')
    
    def save(self, *args, **kwargs):
        try:
            self.full_clean()
        except ValidationError as e:
            raise e
        else:
            super().save(*args, **kwargs)

class Factura(models.Model):
    fecha_compra = models.DateField()
    valor_neto = models.PositiveIntegerField()
    iva = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    archivo = models.FileField(upload_to='documentos/%Y/%m/%d/', default='default.pdf')
    
    def __str__(self):
        return str(self.fecha_compra)

class Categoria(models.Model):
    TIPO_CATEGORIA = [
        (1, "Material escolar"),
        (2, "Libros y recursos educativos"),
        (3, "Mobiliario"),
        (4, "Laboratorio"),
        (5, "Deportes"),
        (6, "Tecnología"),
        (7, "Arte"),
        (8, "Cafetería"),
        (9, "Seguridad"),
        (10, "Aseo") 
    ]
    tipo_categoria = models.PositiveIntegerField(choices=TIPO_CATEGORIA)

    def __str__(self):
        return self.get_tipo_categoria_display()

class Articulo(models.Model):
    codigo = models.CharField(max_length=5, blank=True)
    nombre_articulo = models.CharField(max_length=50)
    cantidad = models.PositiveIntegerField()
    old_quantity = models.PositiveIntegerField(blank=True, null=True)
    precio_unitario = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    factura_detalle = models.ForeignKey(Factura, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    @transaction.atomic
    def save(self, *args, **kwargs):
        # Guardar objetos relacionados antes de guardar el artículo
        # if self.categoria_id:
        #     self.categoria.save()
        # if self.factura_detalle_id:
        #     self.factura_detalle.save()
        
        self.generar_codigo()

        super().save(*args, **kwargs)
    
    def generar_codigo(self):
        if not self.codigo:
            categoria = self.categoria
            if categoria:
                # Obtener el tipo de categoría
                tipo_categoria = categoria.get_tipo_categoria_display()

                # Obtener el número de artículos existentes en la categoría actual
                num_articulos = Articulo.objects.filter(categoria=categoria).count()

                # Generar el código basado en el tipo de categoría y el número de artículos
                codigo = tipo_categoria[0].upper() + str(num_articulos + 1).zfill(4)
                self.codigo = codigo

    def __str__(self):
        return self.codigo

class LogEntry(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey(Articulo, on_delete=models.CASCADE)
    change_type = models.CharField(max_length=10)
    # Otros campos que desees registrar

src/Proyecto_API/api/views.py
from django.db.models.signals import pre_save, post_save
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.http.response import JsonResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.views import View
from .models import *
from .forms import *
import json

# Create your views here.

def login_view(request):
    # Verificar las credenciales del usuario y realizar el inicio de sesión

    # Redirigir a una página específica después del inicio de sesión
    return redirect('home')  # 'home' es la URL a la que se redirigir

@receiver(pre_save, sender=Articulo)
def pre_save_handler(sender, instance, **kwargs):
    if instance.pk is None:
        instance.old_quantity = 0
        change_type = 'Nuevo artículo'
    else:
        try:
            old_instance = Articulo.objects.get(pk=instance.pk)
        except Articulo.DoesNotExist:
            return
        instance.old_quantity = old_instance.cantidad
        if instance.cantidad > old_instance.cantidad:
            change_type = 'Aumento'
        elif instance.cantidad < old_instance.cantidad:
            change_type = 'Reducción'
        else:
            return
    Articulo.objects.filter(pk=instance.pk).update(old_quantity=instance.old_quantity)  # Utilizar update() en lugar de save()
    log_entry = LogEntry(item=instance, change_type=change_type)
    # log_entry.save()

@receiver(post_save, sender=Articulo)
def post_save_handler(sender, instance, created, **kwargs):
    if created:
        return
    try:
        old_instance = Articulo.objects.get(pk=instance.pk)
    except Articulo.DoesNotExist:
        return
    if instance.cantidad == old_instance.cantidad:
        return
    Articulo.objects.filter(pk=instance.pk).update(cantidad=instance.cantidad)  # Utilizar update() en lugar de save()
    change_type = 'Aumento' if instance.cantidad > old_instance.cantidad else 'Reducción'
    log_entry = LogEntry(item=instance, change_type=change_type)
    log_entry.save()


def logs_view(request):
    logs = LogEntry.objects.all().order_by('-timestamp')
    return render(request, 'main/registros.html', {'logs': logs})

def Home(request):
    return render(request = request, template_name="main/index.html")

def Ingresos(request):
    articulos = Articulo.objects.all()
    
    if request.method == 'POST':
        articulo_id = request.POST['articulo']
        cantidad_adicional = request.POST['cantidad']
        
        # Obtén el objeto Articulo seleccionado
        articulo = Articulo.objects.get(id=articulo_id)
        
        # Aumenta la cantidad existente
        articulo.cantidad += int(cantidad_adicional)
        articulo.save()

        # Redirecciona a la página deseada después de agregar la cantidad
        return redirect('registros')
    return render(request=request, template_name="main/ingresos.html", context={'articulos': articulos})

def Egresos(request):
    articulos = Articulo.objects.all()
    
    if request.method == 'POST':
        articulo_id = request.POST['articulo']
        cantidad_adicional = request.POST['cantidad']
        
        # Obtén el objeto Articulo seleccionado
        articulo = Articulo.objects.get(id=articulo_id)
        
        # Aumenta la cantidad existente
        articulo.cantidad -= int(cantidad_adicional)
        articulo.save()

        # Redirecciona a la página deseada después de agregar la cantidad
        return redirect('registros')
    return render(request=request, template_name="main/egresos.html", context={'articulos': articulos})

def Facturas(request):
    facturas = Factura.objects.all()
    return render(request = request, template_name="main/facturas.html", context={'facturas':facturas})

def Products(request):
    articulos = Articulo.objects.all()
    return render(request = request, template_name="main/articulos.html", context={'articulos':articulos})

def crear_articulo(request):
    # Formulario
    articulo_form = ArticuloForm()

    if request.method == 'POST':
        articulo_form = ArticuloForm(request.POST)
        
        if articulo_form.is_valid():
            # Obtener los datos de los formularios
            categoria_id = request.POST.get('categoria')
            articulo_categoria = Categoria.objects.get(id=categoria_id)

            articulo_nombre_articulo = articulo_form.cleaned_data['nombre_articulo']
            articulo_cantidad = articulo_form.cleaned_data['cantidad']
            articulo_precio_unitario = articulo_form.cleaned_data['precio_unitario']
            articulo_total = articulo_form.cleaned_data['total']

            factura_detalle_id = request.POST.get('factura_detalle')
            articulo_factura_detalle = Factura.objects.get(id=factura_detalle_id)

            articulo = Articulo.objects.create(
                categoria=articulo_categoria,
                nombre_articulo=articulo_nombre_articulo,
                cantidad=articulo_cantidad,
                precio_unitario=articulo_precio_unitario,
                total=articulo_total,
                factura_detalle=articulo_factura_detalle,
                old_quantity=0  # Asigna un valor predeterminado al campo old_quantity
            )
            return redirect('articulos')
        
    return render(request, 'main/add_articulo.html', {
        'articulo_form': articulo_form,
    })

def editar_articulo(request, id):
    articulo = Articulo.objects.get(id=id)
    if request.method == 'POST':
        form = ArticuloForm(request.POST, instance=articulo)
        if form.is_valid():
            form.save()
    else:
        form = ArticuloForm(instance=articulo)
    
    context = {'form': form}
    return render(request, 'main/editar_articulo.html', context)

def eliminar_articulo(request, id):
    articulo = Articulo.objects.get(id=id)
    articulo.delete()
    return redirect('articulos')

def crear_factura(request):
    # Formulario
    factura_form = FacturaForm()

    if request.method == 'POST':
        factura_form = FacturaForm(request.POST)
        
        if factura_form.is_valid():
            # Obtener los datos de los formularios
            factura_fecha_compra = factura_form.cleaned_data['fecha_compra']
            factura_valor_neto = factura_form.cleaned_data['valor_neto']
            factura_iva = factura_form.cleaned_data['iva']
            factura_total = factura_form.cleaned_data['total']
            factura_archivo = request.FILES['archivo']
            
            proveedor_id = request.POST.get('proveedor')  # Obtener el ID del proveedor seleccionado del formulario
            proveedor = Proveedor.objects.get(id=proveedor_id)  # Obtener la instancia del proveedor
            
            factura = Factura.objects.create(
                fecha_compra=factura_fecha_compra,
                valor_neto=factura_valor_neto,
                iva=factura_iva,
                total=factura_total,
                archivo=factura_archivo,
                proveedor=proveedor)  # Asignar el proveedor a la factura
            
            return redirect('facturas')

    return render(request, 'main/add_factura.html', {
        'factura_form': factura_form,
    })

def editar_factura(request, id):
    factura = Factura.objects.get(id=id)
    if request.method == 'POST':
        form = FacturaForm(request.POST, instance=factura)
        if form.is_valid():
            form.save()
            # Redirigir o hacer alguna otra acción después de guardar el formulario
    else:
        form = FacturaForm(instance=factura)

    context = {'form': form}
    return render(request, 'main/editar_factura.html', context)

def eliminar_factura(request, id):
    factura = Factura.objects.get(id=id)
    factura.delete()
    # Redirigir o hacer alguna otra acción después de eliminar la factura

def crear_proveedor(request):
    proveedor_form = ProveedorForm()

    if request.method == 'POST':
        proveedor_form = ProveedorForm(request.POST)
        
        if proveedor_form.is_valid():
            provedor_rut = proveedor_form.cleaned_data['rut']
            provedor_nombre = proveedor_form.cleaned_data['nombre']
            provedor_giro = proveedor_form.cleaned_data['giro']
            provedor_correo = proveedor_form.cleaned_data['correo']
            provedor_telefono = proveedor_form.cleaned_data['telefono']
            provedor_celular = proveedor_form.cleaned_data['celular']
            provedor_web = proveedor_form.cleaned_data['web']

            direccion_id = request.POST.get('direccion')
            direccion = Direccion.objects.get(id=direccion_id)

            proveedor = Proveedor.objects.create(
                rut = provedor_rut,
                nombre = provedor_nombre,
                giro = provedor_giro,
                correo = provedor_correo,
                telefono = provedor_telefono,
                celular = provedor_celular,
                web = provedor_web,
                direccion = direccion,
            )
            return redirect('crear_factura')

    return render(request, 'main/add_proveedor.html', {
        'proveedor_form': proveedor_form,
    })

def crear_direccion(request):
    direccion_form = DireccionForm()

    if request.method == 'POST':
        direccion_form = DireccionForm(request.POST)
        
        if direccion_form.is_valid():
            direccion = direccion_form.save()
            return redirect('crear_proveedor')

    return render(request, 'main/add_direccion.html', {
        'direccion_form': direccion_form,
    })

def Catergorias(request):
    categorias = Categoria.objects.all()

src/Proyecto_API/api/templates/main/add_articulo.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Articulo</title>

    <script src="../../static/js/add.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    {% load humanize %}

    <!-- Barra de Navegación -->
    <div class="p-1 bg-dark text-white">
        <div class="row">
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                <div class="d-flex justify-content-center align-items-center">
                    <a href="/api/home">
                        <img src="/static/images/logo.png" alt="" width="50" height="50"
                            class="d-inline-block align-text-top">
                        <a class="navbar-brand" href="/api/home">
                            &nbsp;CTP San Ramón
                        </a>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-center">
                    <a class="navbar-brand" href="#">
                        <p>
                            Desarrollador
                            <p>
                </div>
            </div>
        </div>
    </div>

    <!-- Formulario Factura -->
    <div class="container">
        <div class="d-flex">
            <a href="/api/home">
                <button type="button" class="btn btn-danger mt-3 mb-2">Cancelar</button>
            </a>
        </div>
    </div>

    <div class="container">
        <br>
        <form method="post" action="{% url 'crear_articulo' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ articulo_form.as_p }}

            <!-- Agrega el código JavaScript para calcular el total -->
            <script>
                document.addEventListener("DOMContentLoaded", function () {
                    var cantidadInput = document.getElementById("id_cantidad");
                    var precioUnitarioInput = document.getElementById("id_precio_unitario");
                    var totalInput = document.getElementById("id_total");

                    // Función para calcular el total
                    function calcularTotal() {
                        var cantidad = parseInt(cantidadInput.value);
                        var precioUnitario = parseFloat(precioUnitarioInput.value.replace(/\./g, '').replace(',', '.'));
                        var total = cantidad * precioUnitario;

                        totalInput.value = total.toFixed(2);  // Ajusta el total a dos decimales
                    }

                    // Escucha el evento "input" en los campos de cantidad y precio unitario
                    cantidadInput.addEventListener("input", calcularTotal);
                    precioUnitarioInput.addEventListener("input", calcularTotal);
                });
            </script>

            <br>
            <br>
            <button type="submit" class="btn btn-primary">Agregar Articulo</button>
        </form>
    </div>

    <!-- Optional Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

src/Proyecto_API/api/templates/main/add_direccion.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Factura</title>

    <script src="../../static/js/add.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    <!-- Barra de Navegación -->
    <div class="p-1 bg-dark text-white">
        <div class="row">
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                <div class="d-flex justify-content-center align-items-center">
                    <a href="/api/home">
                        <img src="/static/images/logo.png" alt="" width="50" height="50"
                            class="d-inline-block align-text-top">
                        <a class="navbar-brand" href="/api/home">
                            &nbsp;CTP San Ramón
                        </a>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-center">
                    <a class="navbar-brand" href="#">
                        <p>
                            Desarrollador
                            <p>
                </div>
            </div>
        </div>
    </div>

    <!-- Formulario Factura -->
    <div class="container">
        <div class="d-flex">
            <a href="/api/facturas/views">
                <button type="button" class="btn btn-danger mt-3 mb-2">Cancelar</button>
            </a>
        </div>
    </div>

    <div class="container">
        <h1>Agregar Dirección</h1>
        <br>
        <form method="post" action="{% url 'crear_direccion' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ direccion_form.as_p }}

            <br>
            <br>
            <button type="submit" class="btn btn-primary">Agregar Direccion</button>
        </form>
    </div>


    <!-- Optional Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

src/Proyecto_API/api/templates/main/categorias.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorias</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,1,0" />
</head>

<body>
    <!-- Barra de Navegación -->
    <div class="p-1 bg-dark text-white">
        <div class="row">
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                <div class="d-flex justify-content-center align-items-center">
                    <a href="/api/home">
                        <img src="/static/images/logo.png" alt="" width="50" height="50"
                            class="d-inline-block align-text-top">
                        <a class="navbar-brand" href="/api/home">
                            &nbsp;CTP San Ramón
                        </a>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="text-center">
                    <a class="navbar-brand" href="#">
                        <p>
                            Desarrollador
                            <p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 mx-auto text-center">
            <a href="/api/home">
                <button type="button" class="btn btn-warning m-2">Volver al Inicio</button>
            </a>
        </div>
        <div class="col-md-4">

        </div>
        <div class="col-md-4">

        </div>
    </div>

    <!-- categorias.html -->
    <table class="table">
        <thead>
            <tr>
                <th>Categoría</th>
                <th>Artículos</th>
            </tr>
        </thead>
        <tbody>
            {% for categoria in categorias %}
            <tr>
                <td>{{ categoria.get_tipo_categoria_display }}</td>
                <td>
                    <ul>
                        {% for articulo in categoria.articulo_set.all %}
                        <li>{{ articulo.codigo }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Optional Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

src/Proyecto_API/api/templates/main/login.html
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar Sesión</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    <h2>Iniciar sesión</h2>
    <form method="post">
        {% csrf_token %}
        <label for="username">Usuario:</label>
        <input type="text" id="username" name="username" required><br>
        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required><br>
        <input type="submit" value="Iniciar sesión">
    </form>

    <!-- Optional Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>